# Generated by Django 2.2a1 on 2019-02-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nehapp', '0003_auto_20190203_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
